name: Release
on: [release]
jobs:
  build:
    name: 'Release package to marketplace'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Add git info
        run: |
          git config --global user.email "bot@newbucket.com"
          git config --global user.name "Botty McBotface"

      - name: Publish Extension Pre-Release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npm run publish ${{ github.event.release.tag_name }}

